### ISSUE TITLE
TurnBasedRPG broken in HTML5 Safari

### ISSUE THREAD

**Issue by TheSpydog** [HaxeFlixel/flixel-demos#265] opened 2018-05-19 21:26 UTC
The game displays a black screen (after the initial HF logo) when played in Safari. The JS console shows the following error:
```
TypeError: null is not an object (evaluating 'this.__buffer.get_src().duration')
```
The demo works as expected on Chrome.

**Comment by Gama11** [comment] 2018-05-19 22:05
Hm, that's gonna be a tricky one, as I don't have a Mac to reproduce this. Have you noticed this issue in any of the other demos, or is it somehow specific to just this one?

For what it's worth, that demo is working fine for me in Chrome / Edge / Firefox _and_ Opera.

**Comment by TheSpydog** [comment] 2018-05-19 23:05
Alright, I've gone through all the demos. This issue also appears in the[ FlxTypeText demo](https://haxeflixel.com/demos/FlxTypeText/), the [FlxSound demo](https://haxeflixel.com/demos/FlxSound/) (whenever a button is clicked), and [Mode](https://haxeflixel.com/demos/Mode/) (as soon as a sound is supposed to play).

Safari's JS debugging services are...not great. The stack trace isn't providing anything vaguely useful, but it looks like the offending code is calling `get_length`, which is in the middle of the `openfl.media.Sound` declaration. So it appears the issue is audio related on OpenFL's end, which is odd since Project Jumper also has audio but works fine on Safari...

**Comment by Gama11** [comment] 2018-05-19 23:10
That's very interesting, thanks for going through the trouble of testing all the demos! :)

Since it sounds like this is most likely an issue in OpenFL, or at least not Flixel's fault, it would be ideal if you could reproduce this outside of Flixel with a pure OpenFL project and report it as an issue on the OpenFL repo.

**Comment by Gama11** [comment] 2019-01-22 18:09
Closing this as a duplicate of https://github.com/HaxeFlixel/flixel/issues/2197 so we don't have two issues for this.

**Closed by Gama11** 2019-01-22 18:09 UTC
Labels: Bug
